update
Change-Id: I2390a6a97a8304795c4e4e931ba09201fbd73bbc

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -13,17 +13,21 @@ case "${1}" in
             cp /usr/share/plymouth/deepin-logo.png /usr/share/plymouth/debian-logo.png
         fi
 
+	    update-alternatives --install /usr/share/backgrounds/default_background.jpg \
+		    deepin-default-background /usr/share/backgrounds/desktop.jpg 50
 
-	update-alternatives --install /usr/share/backgrounds/default_background.jpg \
-		deepin-default-background /usr/share/backgrounds/desktop.jpg 50
-	
-	update-alternatives --install /etc/deepin-version \
-		deepin-version /usr/lib/deepin/desktop-version 50
+	    update-alternatives --install /etc/deepin-version \
+		    deepin-version /usr/lib/deepin/desktop-version 50
 
-	if [ -x /usr/sbin/update-initramfs ]
-	then
-		update-initramfs -u
-	fi
+	    if [ -x /usr/sbin/update-initramfs ]
+	    then
+		    update-initramfs -u
+	    fi
+
+        if [ -x /usr/sbin/update-grub ]
+        then
+            /usr/sbin/update-grub || echo "update-grub failed! Ignore..." >&2
+        fi
 		;;
 
 	abort-upgrade|abort-remove|abort-deconfigure)
